language: node_js
node_js:
- 6
- 8
- 10
- stable

stages:
  - test
  - name: deploy

jobs:
  include:
  - stage: deploy
    node_js: stable
    script: skip
    deploy:
      provider: npm
      email: sh3d2.pl@gmail.com
      api_key:
        secure: TCAS2HyX3Yh4UUvW/dJGodhXazx8q6KcJoryN+eCG+2Xcmz7BPRFtmk7DTEadTcZrA/KIXB5IkX09p1cZBj8BaP6kkpnoYPumPzCm9TItbWk3soFboleIRX02Q/egMFk7d6jEy97fgTEx53mZAVl8ZxXjmULeN9UOJal3mZ1NPogt82uSjr1j/I2lOtj9Fju/MwiVs1Q+P7Y+75G1HYtpVHvpU1oeBmFET05Bj/Rkt3NT3zMCAcJe6jbTNM9qSQgcfOTpnAFbvn1gEKl9fRMymYPG6PX/MzKEpH37axNGyvXRraa8bXIoCTZQaPNov3UOQKJc7m59stRemdB+CoWkULLiiaasP34+Bx9CVinREtGxM7gLWOOA7sFGGzQRBaS6P72wWU947GcEv7mVF/UmOIGH8OKZL7FV+ft5cQX3V24W28JdUdxWA3PebIxMq5LOZnxWmPP+5j9/OffxUzcVJgCdhRaMYN2l7NQueWO+Xol7a2N3obI/E7bV6cWulBTDnXOQiUBbDvSZCptN5TC1TTtA8Tcm6zzuVfpS+LctZqbzEnlBmqGwR6NgZdeWFC8QhOUnBUI/8VgYB5+MCHWhSpQOGDiWjUHXb6+wofHxTNlzHnysMBbN8TUioGGGh1KyPi2E6wl1VmGR3zKg5wCFWU0Fo4KDai01Xo62IVTpao=
      on:
        tags: true
        repo: sh3d2/express-rate-limit
