language: node_js
node_js:
  - 6
  - 8
  - 10
  - stable

# wait until after all node.js versions pass before deploying
# https://docs.travis-ci.com/user/build-stages/deploy-npm/

stages:
  - test
  - name: deploy

jobs:
  include:
    - stage: deploy
      node_js: stable
      script: skip
      deploy:
        provider: npm
        email: sh3d2.pl@gmail.com
        api_key:
          secure: EvmRiHaJGVzQDl/L16YpVXwVj2yjPErNHtxKE1F0JdbFUEe52rI+E7oBnuMwUsmzwTfUkdBdDBA/H2JV6roinN6SDjPNyPOb6EL74kSyG+bAMq8M5l0D+RdoTBbAzZo9jTaKEkUEvnQ7oayk1766LXEIeQlowk2A+kAFuQe1gLI2PumMmBq1Fd4Oh3fEoyr+e76zILpquiR7R0Woxa4H2eNRyqDrir/ZPZZI+XdWOFQO1qa0yUH7LY/9lIWf/9A2C+rDM6dTMwHrAnM/vXgbPc4fza7UW1iHZagisEdpqyXibo3SR45aHUAyQE070P2DTb+S1zrtzRgsJGD69CjmpKGzxq9k7aW4MftxVQdfQ3RnHcznTSwEIzFhdV51dsoxsYgCuZJT1WM5i269Y5kscUDVtKSYkETIOujnG8rGB6IqZzF5RP02tyAeevZlmYeHDIF7kaPAEDyEk+NO8C+EOzkgcdbtL1MnZIHlT4STwKcRSgesem2IaYl8mzOtxAFM03AHbgIQzdUA2xPL0QzfmqZY9CUC5fvUgpFeaAxbGIxohsK5IiH5lYVYSYyEwRJ7CUc4KTeovmXXMzzAsBO7RIWm8ujoD6IWmdyRMsYRVPuPwQRQ4lqcKfeUKjH8J5KD4+wE9eJnpm0Waoxpny0tAGWv+uu83cZvQ3ZUPdtWXx0=
        on:
          tags: true
