language: node_js
node_js:
- 6
- 8
- 10
- stable

jobs:
  include:
    - stage: deploy
      node_js: stable
      script: skip
      deploy:
        provider: npm
        email: sh3d2.pl@gmail.com
        api_key:
          secure: Q4BNG5T38emu+fO9iUZa7PFq2yV1FPG2TkU+0Wd6OLFz9TgDxYJcwwfilobGx73QXHV3EkdBiDAWLdjcOWCdmN8NY0Zqj7fsKG//VMyJAC8Al3qO/wH4vNyP6bMSmdCuljAip7bSFuD0nhffXtmlhSVTrxQbDRelFTY2OHUryJpKtDm3tLNtQdDfXAknwc8Ss2JM3KHb7E1dlCE1ghtBM0loNbck/qxvy+oRSMFScMml2S33ak0RVBGcnjBqsL75x8C9lnFtYCT+nyuLszyW8Qa523SxtW5qI1w+Akwik4f5Z4FFiixlFbtARj8lGDxvpDOe66iSlmxjDi4duqqDXaPDE8KsAJ0CM8kpKar10d4nmTE9W6hsajItYq+81u23XKEofpghQ2+sl56lCKIb/AQz8WFddc3kB7SPahf1ElQBBRHjoVTmXeA1e26XQUkKXhK821G0RHMCs+bxaruyyP1bmZ4k0SVsXbqiM+ZfkeU7M+Pyok8h9FO2IXX+uFgt7rLwbajxCQQt52UsBTyOrrkokbbIBGXxj1Jh1OXO/0un/b4h/BrVbtpuqdqndg7rMN9fjNtVmsizCz4mYG9Ju+snZx7rWL9zKdPqGeYl0qDv7NyAxIwqMiJW8GxLS6YhVJGomzn0Y+YG+z4JJLx5FwmxYFMj39BLN+G18S2ZZqM=
        on:
          tags: true
          repo: sh3d2/express-rate-limit
